author = "thrisp/hurrata"
description = "a simple theme for the flotilla framework & associated extensions"
license = "MIT"
name = "halliwell"
source_repo = "n/a yet"
tags = ["flotilla", "simple", "go", "golang"]
